pragma Singleton

// Local.qml
// User-local configuration overrides. Reads JSON from
// `$HOME/.config/quickshell-bar/config.jsonc` and exposes:
//   - `get(key, defaultValue)` — read accessor used by Theme + services
//   - `set(key, value)`        — schedule an override write (debounced)
//   - `reset(key)`             — drop a previously-set override
//   - `resetAll()`             — wipe all overrides (back to defaults)
//
// Hot-reload: the FileView watches the config path. Edits via `set()`
// pipe through a 500 ms debounce — rapid changes (slider drags) coalesce
// into a single file write. External hand-edits also live-reload.
//
// JSONC: `//` line comments and `/* ... */` block comments are stripped
// before JSON.parse, but ONLY outside string literals — URLs containing
// `//` are preserved correctly. The strip regex is string-aware.
//
// Settings page write-back format: minimal canonical JSON with a
// generated header comment. Only keys the user has set are written;
// reset() removes a key entirely so the file shrinks back. Default-
// valued keys are not written — they show up as defaults via `get()`'s
// fallback when no override is present.
//
// First flush per session creates `config.jsonc.bak` from the existing
// content before overwriting. Subsequent flushes don't re-back-up; on
// the next session the cycle repeats so users always have a one-step
// undo.
//
// Malformed JSON: warning logged, last-good `data` retained. No crash.
//
// See `docs/CUSTOMIZATION.md` for the full list of overridable keys.

import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    // Raw parsed JSON object. Initially `{}` so `get()` returns its
    // default during the brief window before FileView fires `onLoaded`.
    property var data: ({})

    // ---- read API ----

    function get(key, defaultValue) {
        if (root.data && root.data[key] !== undefined)
            return root.data[key];
        return defaultValue;
    }

    // ---- write API ----
    //
    // `set()` updates `data` immediately so live preview sees the change
    // right away (Theme bindings re-evaluate on next paint), then schedules
    // a flush. Multiple rapid `set()` calls (slider drag) restart the
    // debounce timer; only the final state hits disk.

    function set(key, value) {
        const next = Object.assign({}, root.data || {});
        next[key] = value;
        root.data = next;
        flushTimer.restart();
    }

    function reset(key) {
        if (!root.data || root.data[key] === undefined) return;
        const next = Object.assign({}, root.data);
        delete next[key];
        root.data = next;
        flushTimer.restart();
    }

    function resetAll() {
        if (!root.data || Object.keys(root.data).length === 0) return;
        root.data = {};
        flushTimer.restart();
    }

    // ---- internals ----

    // Tracked across the lifetime of the qs daemon. First flush() in a
    // session backs up the existing config.jsonc to `.bak`; subsequent
    // flushes skip the backup. Resets to false after `qs` restart.
    property bool _hasBackedUpThisSession: false

    Timer {
        id: flushTimer
        interval: 500
        repeat: false
        onTriggered: root._flush()
    }

    function _flush() {
        // Build canonical JSON from current `data`. Header comment marks
        // the file as Settings-managed so users editing by hand are warned
        // (the docs reinforce this too).
        const stamp = new Date().toISOString();
        const body = JSON.stringify(root.data || {}, null, 2);
        const text =
            "// Generated by quickshell-bar Settings — last save " + stamp + "\n"
            + "// Hand-edits below this line will be overwritten on the next save\n"
            + "// from the Settings page. A backup is saved to config.jsonc.bak\n"
            + "// on the first save of each session.\n"
            + body
            + "\n";

        // First save of the session: snapshot existing file → .bak so the
        // user can roll back if Settings overwrote something they wanted
        // to keep. Skipped if the file doesn't exist yet (no source to
        // back up) or we've already backed up this session.
        if (!root._hasBackedUpThisSession) {
            const existing = configFile.text() || "";
            if (existing.length > 0) {
                bakFile.setText(existing);
            }
            root._hasBackedUpThisSession = true;
        }

        configFile.setText(text);
    }

    // ---- file readers / writers ----

    FileView {
        id: configFile
        path: Quickshell.env("HOME") + "/.config/quickshell-bar/config.jsonc"
        watchChanges: true
        printErrors: false
        onFileChanged: reload()

        onLoaded: {
            try {
                // Strip JSONC comments while preserving string contents.
                // The regex matches three alternatives in order:
                //   1. A complete quoted string (with escape handling) —
                //      preserved verbatim by the replacer.
                //   2. A `//` line-comment to end-of-line.
                //   3. A `/* ... */` block-comment (non-greedy, multi-line).
                // Alternatives 2 and 3 are replaced with empty strings;
                // alternative 1 is returned as-is. Net effect: URLs like
                // "https://example.com" stay intact while
                //   "key": "value", // trailing comment
                // becomes
                //   "key": "value",
                // which JSON.parse accepts cleanly.
                const cleaned = (configFile.text() || "")
                    .replace(/"(?:\\.|[^"\\])*"|\/\/.*$|\/\*[\s\S]*?\*\//gm,
                             m => m.charAt(0) === '"' ? m : "");
                const parsed = JSON.parse(cleaned || "{}");
                root.data = parsed;
            } catch (e) {
                console.warn("[Local] config parse error:", e);
                // Keep `data` at its previous (good) value rather than
                // wiping to `{}` — a typo mid-edit shouldn't reset
                // everything to defaults until the user fixes the JSON.
            }
        }

        onLoadFailed: function(_err) {
            // No file at the expected path = no overrides; defaults stand.
            // Don't log — most users won't have a config and the warning
            // would be noise.
        }
    }

    // Backup target. Same dir as the main config, `.bak` suffix.
    FileView {
        id: bakFile
        path: Quickshell.env("HOME") + "/.config/quickshell-bar/config.jsonc.bak"
        printErrors: false
    }

    Component.onCompleted: configFile.reload()
}
